### ISSUE TITLE
zsh command "ls" can not exit

### ISSUE THREAD

**Issue by onewayticket255** [tbodt/ish#438]
iOS 13 beta 4
iSH 1.0(53)
---
![](https://i.loli.net/2019/07/22/5d355a66860fd68364.png)
---
Update 
iSH 1.0(55)
zsh  works well(solve the problem in version 53)

But, zsh+oh-my-zsh:
![](https://i.loli.net/2019/08/01/5d42ea5811a5374092.jpg)

**Comment by jasonehines** [comment]
I’m also getting this with the motd using zsh.

**Comment by livelaughriley** [comment]
this is happening for me with any command i run with zsh. i can’t CTRL-C out of the command either

**Comment by stek29** [comment]
ZSH gets stuck in sigsuspend loop waiting for `SIGCHLD` which is never delivered to it for some reason (it stays in `task->pending` forever, so sigsuspend just returns, but signal is still not delivered so zsh keeps calling sigsuspend over and over).

It's broken since a8392d5316343d545e91a8a1556e60ca5dcf43a2.

**Comment by tbodt** [comment]
So what I think happened is: zsh calls sigsuspend with a mask that unblocks SIGCHLD, child exits and sends SIGCHLD, sigsuspend stops waiting and resets mask to block SIGCHLD again, and when we get to receive_signals in kernel/calls.c it does nothing because SIGCHLD is now blocked.

**Comment by stek29** [comment]
@tbodt Yeah, that seems correct.
And it was working before a8392d5316343d545e91a8a1556e60ca5dcf43a2 because sigsuspend/sigprocmask were just blocking wrong signals.

**Comment by tbodt** [comment]
Fixed in master

**Comment by livelaughriley** [comment]
@tbodt i’m still having this issue in build 55 (and i’m sorry). 

i’m able to run (from bash) `chsh -s/bin/zsh` and get the zsh prompt to load, but once i type any command and press return, the prompt hangs, and acts like i ran `cat -v`—it just shows raw characters i’m typing. 

i’ve tried closing the app, and once i start it again, i’m greeted with the usual:

```
Welcome to Alpine!                                     
                                                       
You can install packages with: apk add <package>       
                                                       
You may change this message by editing /etc/motd.
```

but without a prompt ☹️

**Comment by mgilan** [comment]
@livelaughriley Do you have oh-my-zsh installed? I had to delete iSH a start from scratch to get it working again. I have only clean ZSH installed at the moment, and that seems to work okay. I’ll install oh-my-zsh tomorrow.

**Comment by livelaughriley** [comment]
@mgilan No, I don't. At first, it was just an oh-my-zsh issue (or at least seemed to be), but now it happens with zsh in general

**Comment by tbodt** [comment]
It works for me perfectly fine without oh-my-zsh.

**Comment by livelaughriley** [comment]
@tbodt are you running iOS 13? if so, what version?

**Comment by tbodt** [comment]
yes, beta 4.

**Comment by stek29** [comment]
@livelaughriley what version of zsh do you have?

**Comment by mgilan** [comment]
I just installed oh-my-zsh, and the shell stopped responding immediately after the setup.

**Comment by livelaughriley** [comment]
@stek29 i’ll be honest i’m a bit hesitant to try and install it again. i have to uninstall iSH and then reinstall it again to be able to use it; i still don’t have a prompt when i close iSH and reopen, so a full uninstall is the only way i currently know of to get myself out of that situation

**Comment by mgilan** [comment]
It’s ok until you don’t set ZSH as your default shell.

**Comment by tbodt** [comment]
Fixed in master, hopefully for real this time.

**Comment by tevino** [comment]
@tbodt It seems that the problem still exists. In my case it will hang if I:

1. start `fish`
2. run `ls` in fish

**Comment by vEnhance** [comment]
Same issue as @tevino on a fresh install, iSh 1.1.1 (build 178).

**Comment by tevino** [comment]
Ping @tbodt for awareness
