### ISSUE TITLE
Mosh crashes after connecting to a server

### ISSUE THREAD

**Issue by Styden** [tbodt/ish#440]
When i try to connect to a mosh server, it connects (sure i saw my remote welcome page on bash) then it crashed half a second later.
Crash log : https://pastebin.com/kW5CC5Kt
(Btw, do i need a cert with custom entitlements to sign ish properly ? Because when i try to sign and install it with my cert ish crashes at startup, but with testflight it's working perfectly)

**Comment by leeramsay** [comment]
Mosh crashes for me, too.

It used to work with iSH, but I don’t use it often enough to know exactly what release broke it.

I suspect it may have been working on release 52 but it may have been earlier.

**Comment by Styden** [comment]
Ah ok, thanks for the answer. What do you think about the custom entitlements cert ? Is it required to make the app working ? Or what else could be the problem ?

**Comment by tbodt** [comment]
I don't know why the app doesn't work when you try to sideload it. All I know is it works for me with my paid dev account. Pretty sure it used to work fine with a free account. Could you open a new issue for that?

**Comment by stek29** [comment]
@Styden it works perfectly fine with free account for me (via Xcode).

**Comment by tbodt** [comment]
Crash fixed in master.

**Comment by NightMachinary** [comment]
This still happens for me. I just installed ish today, so it should contain that fix.

**Comment by tbodt** [comment]
@NightMachinary Probably a new bug, please open a new issue and include a crash dump
