### ISSUE TITLE
SSL Error

### ISSUE THREAD

**Issue by josete89** [tbodt/ish#73]
Hi

I was trying to install kubectl and I got this error from curl

curl: (56) LibreSSL SSL_read: error:06FFF064:digital e
nvelope routines:CRYPTO_internal:bad decrypt, errno 0

**Comment by Mnpn03** [comment]
I’m not sure if you’re running the TestFlight version or building it yourself. HTTPS with curl seems to have been fixed in the master branch and will be available in the next TestFlight build, as far as I’m aware.
—
Ah, #67.

**Comment by tbodt** [comment]
Yup, it's fixed in master.

**Comment by josete89** [comment]
Hmm strange I compiled from master and is still happening to me. I have iOS 12 installed.
